### ISSUE TITLE
Not able to import easily as other library project can do

### ISSUE THREAD

**Issue by ShreyashPromact** [Quinny898/PersistentSearch#11]
Please update the project structure as separate for library project and separate for sample app. Because right now it is not easy to import it in to the Eclipse or Studio. Please update it.

**Comment by Quinny898** [comment]
Android studio has a guide in the readme and Eclipse just needs one checkbox unticking. Not exactly hard.

**Comment by ShreyashPromact** [comment]
I guess, you just have commit the information. Thanks for updating it on readme.md file.

**Comment by rohannexialabs** [comment]
Hi, first of all, excellent library, thanks for that. However, the information in the readme is not complete. I have never added a repository in Android Studio before, so, I didn't know how to add the Sonatype repository . Thus, it was very frustrating for me to add a dependency for your library since I was getting library not found everytime.

Anyhow, after trying for an hour, I figured out where to add the code and make the app work. I have put an answer on stackoverflow with code of my gradle file. If you want, you can include it in the readme file for other users.  http://stackoverflow.com/a/30637170/1979347. Thanks again for your work.

Regards,
Rohan
