### ISSUE TITLE
Multiple dex files define Lcom/balysv/materialmenu/MaterialMenu;

### ISSUE THREAD

**Issue by ikakus** [Quinny898/PersistentSearch#33]
Multiple dex files define Lcom/balysv/materialmenu/MaterialMenu; error is thrown when using with 
'com.balysv.materialmenu:material-menu-toolbar:1.5.1' library

**Comment by Quinny898** [comment]
The library includes all the relevant classes from MaterialMenu, you don't need to import it again

**Comment by jschleppy** [comment]
I also can't use this library as is since I also am already using the full Material Menu Toolbar library. There are classes yours doesn't have that the full library from balysv uses. Regardless though, it's cleaner for you to not include it and to simply add it as an additional gradle requirement for us to use.

Where both of these would be needed to use your library:
compile 'com.quinny898.library.persistentsearch:library:1.0.0-SNAPSHOT'
compile 'com.balysv.materialmenu:material-menu-toolbar:1.5.4'

**Comment by Quinny898** [comment]
Fixed in the update
