### ISSUE TITLE
change the gravity of searchBox?

### ISSUE THREAD

**Issue by TheLoyalCruel** [Quinny898/PersistentSearch#61]
and would you please tell me how to change the gravity of editText in the searchBox! I mean RTL!
another question is: how to change the side that Revealing and Hiding starts! i mean left to right | right to left?
thanks...

**Comment by TheLoyalCruel** [comment]
you know...  I found my the way of revealing! and I can change the gravity of search edittext but I should use library locally and no more gradle dependency... that causes lots of bugs in my app!
can you help?

**Comment by Quinny898** [comment]
Assuming you're just setting the RTL in the code, you can access any view in the searchbox by doing searchbox.findViewById(...)
If you're using XML you can override it by just copying the XML you want to change into your layout, and it will compile that one instead of the library one, without having to include the rest of the library (except in Gradle)
